services:
  mu_php_web:
    image: chaudevops/mu-website:latest # Point to the image the Action will build
    container_name: mu_php_web
    ports:
      - "8888:80"
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - DB_HOST=mu_mssql             # This matches the DB service name
      - DB_PASSWORD=MuOnline@DevOps2024! 
    networks:
      - mu-network

networks:
  mu-network:
    external: true
    