version: '3.8'

services:
  # Web Server (CMS)
  mu_php_web:
    build: .
    container_name: mu_php_web
    ports:
      - "8888:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - DB_HOST=mu_mssql
      - DB_PASSWORD=MuOnline123!
    depends_on:
      - mu_mssql

  # SQL Server (Database)
  mu_mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mu_mssql
    # No platform tag needed for Intel, or use linux/amd64
    user: root 
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MuOnline@DevOps2024!  # Stronger password required by full MSSQL
    volumes:
      - ./db-data:/var/opt/mssql/backup
      - mssql_data:/var/opt/mssql/data

volumes:
  mssql_data:

networks:
  default:
    external:
      name: mu-network